public class Exception1 {
    public Exception1(String var) {
    }
/*
int square=0;
int rem;
    private void correct(int a) {
       square=a*a;
       rem=square%100;
       if(rem==a){
           System.out.println("Number is auto");
       }else{
           throw new ArithmeticException ("Not auto number");
       }

    }
*/

    public static void main(String[] args) {
        // Scanner sc=new Scanner(System.in);
     //   Exception e = new Exception();
       /* System.out.println("Enter the number");
        int a= sc.nextInt();

        try {
            e.correct(a);
        }catch (ArithmeticException e1){
            e1.printStackTrace();
            System.out.println("ArithmeticException Found");
        }
*/
//        try{
//            e.findfile();
//        }catch(FileNotFoundException e1){
//            e1.printStackTrace();
//            System.out.println("File not found");
//        }
//    }
//
//    private void findfile() throws FileNotFoundException{
//        File f=new File("Method Overloading.pdf");
//        FileInputStream file=new FileInputStream(f);
//    }


    }
}
